server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul

zuul:
  routes:
    api-url:
      path: /api-url/**
      url: http://localhost:8080/
    service-id:
      path: /api-service-id/**
      serviceId: client
    feign:
      path: /api-feign/**
      serviceId: feign
      
